### ISSUE TITLE
st-cli options doesn't work

### ISSUE THREAD

**Issue by ToxicFrog** [syncthing/syncthing-cli#8]
st-cli HEAD (as of this writing), st 0.10.29.

st-cli options dump shows default values (0/false/"") for everything. st-cli options set foo is a no-op.

**Comment by AudriusButkevicius** [comment]
As it's being build it fetches the dependencies, which are probably dependencies straight from master, hence probably not compatible with the older version such as 0.10.29 due to the json key renames.

I don't want to maintain different versions of the cli for different versions of syncthing as it's a lot of work, hence we can assume that the code here is for reference, for the end user compile himself.
I wouldn't mind if someone would take up the responsibility of vendoring dependencies and tagging releases and releasing, in case there is someone who is interested.

The way to compile the right version would be to checkout syncthing 0.10.29 on your gopath, so that the internal packages would match the version, and then rebuild cli (you might have to check out an older version of the cli too due to the fix I just pushed).
